// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e0815f4b-7ce5-4bd1-b45b-8201556ca2ce";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDisChange();
void onTimChange();
void onRelayChange();

float dis;
CloudSchedule tim;
bool relay;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dis, READWRITE, ON_CHANGE, onDisChange);
  ArduinoCloud.addProperty(tim, READWRITE, ON_CHANGE, onTimChange);
  ArduinoCloud.addProperty(relay, READWRITE, ON_CHANGE, onRelayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
